version: '3'

services:
  glowdb:
    container_name: glowdb
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - glowdb
    env_file:
      - .env
    volumes:
      - ./:/app

  bucket:
    image: quay.io/minio/minio:latest
    container_name: bucket
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - glowdb
    volumes:
      - ~/terabytes:/data
    command: server /data --console-address ":9001"

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - glowdb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/dist:/usr/share/nginx/html:ro
    depends_on:
      - glowdb
      - bucket

networks:
  glowdb:
    driver: bridge